### ISSUE TITLE
Modifier la variable d'environnement spécifique au dashboard

### ISSUE THREAD

**Issue by loiclaudet** [DL0dz/eStarWars#13]
On écrit actuellement : 

``` js
.limit(process.env.LIMIT_PRODUCTS * 2)
```

C'est absurde. Nous devons : 
- soit ajouter une nouvelle variable d'environnement
- soit utiliser `LIMIT_PRODUCTS` pour le dashboard

Quel est ton avis @PierrickGT ?

**Comment by PierrickGT** [comment]
Tout dépend si on décide d'utiliser le lazy loading ou une pagination non ?
Mais sinon oui, je pense qu'il faudrait une nouvelle variable d'environnement qui nous permette d'afficher plus de produits.

**Comment by loiclaudet** [comment]
Ok, certainement la pagination. Oui pour la nouvelle variable.
